### ISSUE TITLE
 scaffold raises PermissionError on Windows

### ISSUE THREAD

**Issue by rdmolony** [ploomber/scaffold#5]
Tracking ploomber/ploomber#323

**Comment by edublancas** [comment]
Not sure about this error, will publish a new version to fix `IsADirectoryError` and will take a look at this one later.

**Comment by rdmolony** [comment]
Thanks Eduardo, I’ll have a dig around, will post any ideas here

**Comment by edublancas** [comment]
Update: While working on adding Windows to the continuous integration test suite, I realized this problem happens with Python 3.9.
